"""create status tables

Revision ID: 2bad9bb33736
Revises: 9604fc227dbe
Create Date: 2026-03-18 21:32:59.383756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bad9bb33736'
down_revision: Union[str, Sequence[str], None] = '9604fc227dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodekey_node_id'), table_name='nodekey')
    op.drop_table('nodekey')
    op.drop_table('node')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('node_pkey'))
    )
    op.create_table('nodekey',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('secret_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('nodekey_node_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('nodekey_pkey'))
    )
    op.create_index(op.f('ix_nodekey_node_id'), 'nodekey', ['node_id'], unique=False)
    # ### end Alembic commands ###
