"""test upgrade

Revision ID: 4e7d3784b89f
Revises: 36895688534e
Create Date: 2026-02-22 21:34:46.895463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4e7d3784b89f'
down_revision: Union[str, Sequence[str], None] = '36895688534e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('userkey', 'kid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userkey', 'kid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
