"""update user tables

Revision ID: 950a8c1da12b
Revises: 6cff5efda473
Create Date: 2026-03-18 22:07:48.067230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '950a8c1da12b'
down_revision: Union[str, Sequence[str], None] = '6cff5efda473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'has_2fa_auth',
        sa.Boolean(),
        nullable=False,
        server_default='false'   # ← add this
    ))
    op.alter_column('user', 'has_2fa_auth', server_default=None)
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'has_2FA_auth')
    op.alter_column('userkey', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_userkey_name'), 'userkey', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userkey_name'), table_name='userkey')
    op.alter_column('userkey', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('user', sa.Column('has_2FA_auth', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'has_2fa_auth')
    # ### end Alembic commands ###
