"""update user table

Revision ID: cf507c2298b2
Revises: 3d7bce504480
Create Date: 2026-05-17 13:36:11.980576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf507c2298b2'
down_revision: Union[str, Sequence[str], None] = '3d7bce504480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_type'), table_name='notification')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_servicecheckhistory_service_id'), table_name='servicecheckhistory')
    op.create_index('ix_servicecheckhistory_service_checked', 'servicecheckhistory', ['service_id', 'checked_at'], unique=False)
    op.add_column('userkey', sa.Column('last_used', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('userkey_user_id_fkey'), 'userkey', type_='foreignkey')
    op.create_foreign_key(None, 'userkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userkey', type_='foreignkey')
    op.create_foreign_key(op.f('userkey_user_id_fkey'), 'userkey', 'user', ['user_id'], ['id'])
    op.drop_column('userkey', 'last_used')
    op.drop_index('ix_servicecheckhistory_service_checked', table_name='servicecheckhistory')
    op.create_index(op.f('ix_servicecheckhistory_service_id'), 'servicecheckhistory', ['service_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('notification_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_pkey'))
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_type'), 'notification', ['type'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    # ### end Alembic commands ###
