name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: deploy
          key: ${{ secrets.DEPLOY_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo /usr/local/bin/andromeda-deploy-fixperms
            git -C /opt/andromeda pull origin main
            sudo /opt/andromeda/venv/bin/pip install -r /opt/andromeda/requirements.txt
            sudo /opt/andromeda/venv/bin/pip install -e /opt/andromeda
            cd /opt/andromeda && sudo -E /opt/andromeda/venv/bin/alembic upgrade head

            sudo /usr/local/bin/andromeda-deploy-setbuild ${GITHUB_SHA::7}

            sudo systemctl restart andromeda
            sudo /usr/local/bin/andromeda-deploy-resetperms
